//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrossPlanetDesktop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CrossPlanetDbEntities : DbContext
    {
        public CrossPlanetDbEntities()
            : base("name=CrossPlanetDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EngineLogs> EngineLogs { get; set; }
        public virtual DbSet<Point> Point { get; set; }
        public virtual DbSet<ResoursesLogs> ResoursesLogs { get; set; }
        public virtual DbSet<TourPoints> TourPoints { get; set; }
        public virtual DbSet<TourTask> TourTask { get; set; }
    }
}
