//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrossPlanetDesktop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EngineLogs
    {
        public int Id { get; set; }
        public int FurlCount { get; set; }
        public int Temperature { get; set; }
        public System.DateTime Date { get; set; }
    }
}
